// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;


RcppExport SEXP _rcpp_module_boot_stan_fit4case_1_MM_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4case_2_1M_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4case_2_M1_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4case_3_11_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4case_4_M0_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4case_5_10_mod();
RcppExport SEXP _rcpp_module_boot_stan_fit4model_mod();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_stan_fit4case_1_MM_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4case_1_MM_mod, 0},
    {"_rcpp_module_boot_stan_fit4case_2_1M_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4case_2_1M_mod, 0},
    {"_rcpp_module_boot_stan_fit4case_2_M1_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4case_2_M1_mod, 0},
    {"_rcpp_module_boot_stan_fit4case_3_11_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4case_3_11_mod, 0},
    {"_rcpp_module_boot_stan_fit4case_4_M0_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4case_4_M0_mod, 0},
    {"_rcpp_module_boot_stan_fit4case_5_10_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4case_5_10_mod, 0},
    {"_rcpp_module_boot_stan_fit4model_mod", (DL_FUNC) &_rcpp_module_boot_stan_fit4model_mod, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_BINtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
